- name: install docker dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
- name: add apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: get lsb_release
  command: lsb_release -cs
  register: lsb_release
- name: add apt-repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_release.stdout}} stable"
    state: present
- name: install docker
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: append docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- name: reset ssh connection
  meta: reset_connection