- name: create disk
  gcp_compute_disk:
    name: "{{instance_name}}"
    size_gb: "{{ disk_size | default(24) }}"
    source_image: "{{ os_image }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk